// This file has been autogenerated from a class added in the UI designer.

using System;
using System.ComponentModel;
using Foundation;
using SharedCode.DI;
using SharedCode.ViewModel;
using UIKit;

namespace MvvmTookitDemoAppiOS
{
	public partial class CommentsViewController : UIViewController
	{
        public CommentViewModel viewModel = IocService.GetService<CommentViewModel>();
		public CommentsViewController (IntPtr handle) : base (handle)
		{
            viewModel.PropertyChanged += updateUi;
            Console.WriteLine("finish instantiate");
		}
        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            //viewModel.PropertyChanged += updateUi;
            requestButton.TouchUpInside += (object sender, EventArgs e) =>
            {
                viewModel.RequestNewComment();
            };
            Console.WriteLine("commentsdidload");
        }

        public void updateUi(object sender, PropertyChangedEventArgs e)
        {
            idLabel.Text = viewModel.Comment.id.ToString();
            nameLabel.Text = viewModel.Comment.name;
            emailLabel.Text = viewModel.Comment.email;
            bodyLabel.Text = viewModel.Comment.body;
        }
    }
}
